version: '3'
services:
  server-db-2:
    image: postgres:latest
    container_name: server-db-2
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: moikk_social_app
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d

  moikk-social-app:
    build: .
    container_name: moikk-social-app
    ports:
      - "8080:8080"
    depends_on:
      - server-db-2
